export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as CompanyDetails } from './CompanyDetails';
export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Services } from './Services';
export { default as RealisationsSection } from './RealisationsSection';
export { default as Contact } from './Contact';
export { default as AvisGoogle } from './AvisGoogle';
